### ISSUE TITLE
[TODO] Code Cleanup

### ISSUE THREAD

**Issue by samuelgrant** [samuelgrant/Imperium-Incursions-Waitlist#48]
Use `.select()` within the controllers to limit what is returned to users on each page. 

### Checklist:
- [x] Index Page 
  - Look at combining the FC and User settings calls into a single call. 
    - Only return FC information to people with the correct roles.
  - Remove the `async: false` flags, and call various get data methods from within the `.done()` methods on the ajax calls.
  -  Force the waiting pilots window to update when FCs kick pilots.
- [x] Pilot Select only need to show: 
   - Pilots
     - Character ID
     - Character Name
     - EsiValid
- [x] Account Settings, Pilot Fits & My Fits:
  - allowsJabberNotifications
  - Fits: 
     - description
     - id
     - typeId
     - HullType
- [x] `/Admin/Settings`
  - Everything here is fine except for hulls -> `fits` and hulls -> `shipSkills` array.
- [x] User Management
  - Roles is fine
  - userIndex
  - users: (aka accounts)
    - id
    - name
    - account_roles: (id, name)
    - last login
    - pilots
      - character ID
      - name
      - corporation: (id, name, alliance: (id, name))
- [x] Bans 
  - ban admin (id, name)
  - banned account (id, name, pilots (ids, name ) - only used for the banned account icon)
  - Expires at
  - reason

- [x] Make a special function that takes in an `AccountName` and all pilots attached to an account. Then return a single pilot based on:
   - The pilot with the name that matches the account name
   - If the former condition cannot be met, the first pilot passed to the helper function
