### ISSUE TITLE
[TODO]  Use attribute routing for the FleetsController so it matches other controllers.

### ISSUE THREAD

**Issue by samuelgrant** [samuelgrant/Imperium-Incursions-Waitlist#54]
- [x] Use a master route on the controller: `[Route("/fleets/{id}")]`
- [x] Use the appropriate attributes on each method: eg `[HttpMethod("cyno/{cynoId})]`
- [x] Ensure the view still functions correctly
- [x] Remove any unclean code
